sudo: required

# Blacklist Sharelatex branches
branches:
    except:
        - /^sharelatex-.*$/

install:
    - sudo apt-get install -y --no-install-recommends texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra texlive-lang-german latex-xcolor pgf

before_script:
    - wget http://mirrors.ctan.org/macros/latex/contrib/tablefootnote.zip
    - unzip tablefootnote.zip
    - cd tablefootnote
    - tex tablefootnote.dtx
    - mkdir -p ~/texmf/tex/latex/tablefootnote
    - mv *.sty ~/texmf/tex/latex/tablefootnote/
    - cd ../
    - wget http://mirrors.ctan.org/macros/latex/contrib/siunitx.zip
    - unzip siunitx.zip
    - cd siunitx
    - tex siunitx.dtx
    - mkdir -p ~/texmf/tex/latex/siunitx
    - mv *.sty ~/texmf/tex/latex/siunitx/
    - mv *.cfg ~/texmf/tex/latex/siunitx/
    - cd ../
    - wget http://mirrors.ctan.org/macros/latex/contrib/etoolbox.zip
    - unzip etoolbox.zip
    - cd etoolbox
    - mkdir -p ~/texmf/tex/latex/etoolbox
    - mv *.sty ~/texmf/tex/latex/etoolbox/
    - cd ../
    - wget http://mirrors.dotsrc.org/ctan/macros/latex/contrib/oberdiek/ltxcmds.dtx
    - tex ltxcmds.dtx
    - mkdir -p ~/texmf/tex/latex/ltxcmds
    - mv *.sty ~/texmf/tex/latex/ltxcmds/
    - wget http://mirrors.dotsrc.org/ctan/macros/latex/contrib/oberdiek/letltxmacro.dtx
    - tex letltxmacro.dtx
    - mkdir -p ~/texmf/tex/latex/letltxmacro
    - mv *.sty ~/texmf/tex/latex/letltxmacro/
    - cd ~/texmf; mktexlsr

script:
    - cd ~/build/Lauszus/SpacecraftInstrumentationSystems30320; make all -j2
